public enum SortField {
    FOUR_AND_FIVE_WICKET,ECONOMY_RATE,RUNS, AVG,STRIKE_RATE , FOURS_AND_SIX, STRIKING_RATES_WITH_FOURS_AND_SIX,
    STRIKING_RATES_WITH_AVERAGES, BOWLING_AVERAGE, WICKETS_AND_AVERAGE, BATTING_AND_BOWLING_AVG, ALL_ROUNDER;
}
